export function addMessages() {
  Blockly.Msg["TSUMICKY_OLED_HW_I2C_INIT"] = "%1 のハードウェアI2C接続の %2 のOLEDを初期化する";
  Blockly.Msg["TSUMICKY_OLED_HW_I2C_INIT_TOOLTIP"] = "I2C接続のOLEDディスプレイを初期化します。SDA/SCLのピン番号はデフォルトの値を使用します。";
  Blockly.Msg["TSUMICKY_OLED_HW_I2C_INIT_PIN"] = "%1 のハードウェアI2C接続の %2 のOLEDを初期化する: SDA %3 番ピン SCL %4 番ピン";
  Blockly.Msg["TSUMICKY_OLED_HW_I2C_INIT_PIN_TOOLTIP"] = "SDA/SCLのピン番号を指定して、I2C接続のOLEDディスプレイを初期化します。";
  Blockly.Msg["TSUMICKY_OLED_HW_SPI_INIT"] = "%1 のハードウェアSPI接続の %2 のOLEDを初期化する:DC %3 番ピン CS %4 番ピン RES %5 番ピン";
  Blockly.Msg["TSUMICKY_OLED_HW_SPI_INIT_TOOLTIP"] = "SPI接続のOLEDディスプレイを初期化します。";
  Blockly.Msg["TSUMICKY_OLED_HW_SPI_INIT_PIN"] = "%1 のハードウェアSPI接続の %2 のOLEDを初期化する:SDA %3 番ピン SCK %4 番ピン DC %5 番ピン CS %6 番ピン RES %7 番ピン";
  Blockly.Msg["TSUMICKY_OLED_HW_SPI_INIT_PIN_TOOLTIP"] = "SDA/SCKのピン番号を指定して、SPI接続のOLEDディスプレイを初期化します。";
  Blockly.Msg["TSUMICKY_OLED_TYPE_SSD1306_128X64"] = "SSD1306, 128x64ピクセル";
  Blockly.Msg["TSUMICKY_OLED_TYPE_SSD1306_128X32"] = "SSD1306, 128x32ピクセル";
  Blockly.Msg["TSUMICKY_OLED_TYPE_SH1106_128X64"] = "SH1106, 128x64ピクセル";
  Blockly.Msg["TSUMICKY_OLED_DRAW_PIXEL"] = "%1 のOLEDに点を描画する: %2 x %3 y %4";
  Blockly.Msg["TSUMICKY_OLED_DRAW_PIXEL_TOOLTIP"] = "OLEDディスプレイに点を描画します。";
  Blockly.Msg["TSUMICKY_OLED_DRAW_LINE"] = "%1 のOLEDに線を描画する: %2 x1 %3 y1 %4 x2 %5 y2 %6";
  Blockly.Msg["TSUMICKY_OLED_DRAW_LINE_TOOLTIP"] = "OLEDディスプレイに直線を描画します。\nx1とy1で片方の端の座標を指定し、x2とy2でもう片方の端の座標を指定します。";
  Blockly.Msg["TSUMICKY_OLED_DRAW_FRAME"] = "%1 のOLEDに四角を描画する: %2 x %3 y %4 幅 %5 高さ %6";
  Blockly.Msg["TSUMICKY_OLED_DRAW_FRAME_TOOLTIP"] = "OLEDディスプレイに四角(枠のみ)を描画します。xとyで左上の端の座標を指定します。"
  Blockly.Msg["TSUMICKY_OLED_DRAW_BOX"] = "%1 のOLEDに塗りつぶした四角を描画する: %2 x %3 y %4 幅 %5 高さ %6";
  Blockly.Msg["TSUMICKY_OLED_DRAW_BOX_TOOLTIP"] = "OLEDディスプレイに内部を塗りつぶした四角を描画します。xとyで左上の端の座標を指定します。"
  Blockly.Msg["TSUMICKY_OLED_DRAW_CIRCLE"] = "%1 のOLEDに円を描画する: %2 x %3 y %4 半径 %5";
  Blockly.Msg["TSUMICKY_OLED_DRAW_CIRCLE_TOOLTIP"] = "OLEDディスプレイに円(周囲だけ)を描画します。"
  Blockly.Msg["TSUMICKY_OLED_DRAW_DISC"] = "%1 のOLEDに塗りつぶした円を描画する: %2 x %3 y %4 半径 %5";
  Blockly.Msg["TSUMICKY_OLED_DRAW_DISC_TOOLTIP"] = "OLEDディスプレイに内部を塗りつぶした円を描画します。"
  Blockly.Msg["TSUMICKY_OLED_SET_FONT"] = "%1 のOLEDのフォントを %2 にする";
  Blockly.Msg["TSUMICKY_OLED_SET_FONT_TOOLTIP"] = "Arduinoファームウェアのマイコンで、OLEDに文字を表示する際のフォントを選択します。\n英数字を表示する際には英数字フォント、日本語を表示する際には日本語フォントに切り替える必要があります。";
  Blockly.Msg["TSUMICKY_OLED_SET_FONT_RPI"] = "%1 のOLEDのフォントを %2 にする";
  Blockly.Msg["TSUMICKY_OLED_SET_FONT_RPI_TOOLTIP"] = "Blinkaファームウェアのマイコンで、OLEDに文字を表示する際のフォントを選択します。";
  Blockly.Msg["TSUMICKY_OLED_FONT_6X10_TF"] = "英数字, 6x10ピクセル";
  Blockly.Msg["TSUMICKY_OLED_FONT_7X13_TF"] = "英数字, 7x13ピクセル";
  Blockly.Msg["TSUMICKY_OLED_FONT_F10_T_JAPANESE"] = "日本語, 10ピクセル, 通常";
  Blockly.Msg["TSUMICKY_OLED_FONT_F12_T_JAPANESE"] = "日本語, 12ピクセル, 通常";
  Blockly.Msg["TSUMICKY_OLED_FONT_F16_T_JAPANESE"] = "日本語, 16ピクセル, 通常";
  Blockly.Msg["TSUMICKY_OLED_FONT_DEJAVU_SANS_8"] = "DejaVuSans、8ピクセル";
  Blockly.Msg["TSUMICKY_OLED_FONT_DEJAVU_SANS_12"] = "DejaVuSans、12ピクセル";
  Blockly.Msg["TSUMICKY_OLED_FONT_DEJAVU_SANS_16"] = "DejaVuSans、16ピクセル";
  Blockly.Msg["TSUMICKY_OLED_FONT_IPA_MINCHO_12"] = "IPA明朝、12ピクセル";
  Blockly.Msg["TSUMICKY_OLED_FONT_IPA_MINCHO_16"] = "IPA明朝、16ピクセル";
  Blockly.Msg["TSUMICKY_OLED_FONT_IPA_GOTHIC_12"] = "IPAゴシック、12ピクセル";
  Blockly.Msg["TSUMICKY_OLED_FONT_IPA_GOTHIC_16"] = "IPAゴシック、16ピクセル";
  Blockly.Msg["TSUMICKY_OLED_SET_CURSOR"] = "%1 のOLEDのカーソル位置を設定する: X= %2 Y= %3";
  Blockly.Msg["TSUMICKY_OLED_SET_CURSOR_TOOLTIP"] = "OLEDに文字を表示する際のカーソル位置を設定します。";
  Blockly.Msg["TSUMICKY_OLED_PRINT"] = "%1 のOLEDに %2 の文字列を描画する";
  Blockly.Msg["TSUMICKY_OLED_PRINT_TOOLTIP"] = "OLEDに文字列を描画します。"
  Blockly.Msg["TSUMICKY_OLED_SEND_BUFFER"] = "%1 のOLEDの描画結果を表示する";
  Blockly.Msg["TSUMICKY_OLED_SEND_BUFFER_TOOLTIP"] = "線や文字などの描画結果をOLEDに表示します。";
  Blockly.Msg["TSUMICKY_OLED_CLEAR_DISPLAY"] = "%1 のOLEDをクリアする";
  Blockly.Msg["TSUMICKY_OLED_CLEAR_DISPLAY_TOOLTIP"] = "OLEDの表示内容をすべてクリアします。"
  Blockly.Msg["TSUMICKY_OLED_CLEAR_BUFFER"] = "%1 のOLEDのバッファをクリアする";
  Blockly.Msg["TSUMICKY_OLED_CLEAR_BUFFER_TOOLTIP"] = "OLEDの表示内容を記憶しているバッファをクリアします。\n現時点で表示されているものはそのままになります。"
};
