export function addMessages() {
  Blockly.Msg["TSUMICKY_CATEGORY_MPL_CHART_ELEMENT"] = "Chart element";
  Blockly.Msg["TSUMICKY_MPL_CHART_ELEMENT_FIGURE_TITLE"] = "set the title of the entire chart to %1 %2";
  Blockly.Msg["TSUMICKY_MPL_CHART_ELEMENT_FIGURE_TITLE_TOOLTIP"] = "Add a title to the entire chart. \nIf you want to add a title to each individual graph, use the 'Set title to row x column x' block.";
  Blockly.Msg["TSUMICKY_MPL_CHART_ELEMENT_TITLE"] = "set the title of the chart at row %1 column %2 to %3 %4"
  Blockly.Msg["TSUMICKY_MPL_CHART_ELEMENT_TITLE_TOOLTIP"] = "Set the title of the chart."
  Blockly.Msg["TSUMICKY_MPL_CHART_ELEMENT_LEGEND"] = "show legend for chart at row %1 column %2 %3 title %4 position %5 %6 ncol %7";
  Blockly.Msg["TSUMICKY_MPL_CHART_ELEMENT_LEGEND_TOOLTIP"] = "Add a legend to the chart.";
  Blockly.Msg["TSUMICKY_MPL_CHART_ELEMENT_LEGEND_LOC_BEST"] = "best";
  Blockly.Msg["TSUMICKY_MPL_CHART_ELEMENT_LEGEND_LOC_UPPER_LEFT"] = "upper left";
  Blockly.Msg["TSUMICKY_MPL_CHART_ELEMENT_LEGEND_LOC_UPPER_CENTER"] = "upper center";
  Blockly.Msg["TSUMICKY_MPL_CHART_ELEMENT_LEGEND_LOC_UPPER_RIGHT"] = "upper right";
  Blockly.Msg["TSUMICKY_MPL_CHART_ELEMENT_LEGEND_LOC_CENTER_LEFT"] = "center left";
  Blockly.Msg["TSUMICKY_MPL_CHART_ELEMENT_LEGEND_LOC_CENTER"] = "center";
  Blockly.Msg["TSUMICKY_MPL_CHART_ELEMENT_LEGEND_LOC_CENTER_RIGHT"] = "center right";
  Blockly.Msg["TSUMICKY_MPL_CHART_ELEMENT_LEGEND_LOC_LOWER_LEFT"] = "lower left";
  Blockly.Msg["TSUMICKY_MPL_CHART_ELEMENT_LEGEND_LOC_LOWER_CENTER"] = "lower center";
  Blockly.Msg["TSUMICKY_MPL_CHART_ELEMENT_LEGEND_LOC_LOWER_RIGHT"] = "lower right";
  Blockly.Msg["TSUMICKY_MPL_CHART_ELEMENT_AXIS_X"] = "x-axis";
  Blockly.Msg["TSUMICKY_MPL_CHART_ELEMENT_AXIS_Y"] = "y-axis";
  Blockly.Msg["TSUMICKY_MPL_CHART_ELEMENT_AXIS_LABEL"] = "label %3 %4 of chart at row %1 column %2 to %5 %6"
  Blockly.Msg["TSUMICKY_MPL_CHART_ELEMENT_AXIS_LABEL_TOOLTIP"] = "Set the labels for the X-axis and Y-axis.";
  Blockly.Msg["TSUMICKY_MPL_CHART_ELEMENT_TICKS"] = "set the ticks of %3 %4 of the graph at row %1 column %2 to %5 %6";
  Blockly.Msg["TSUMICKY_MPL_CHART_ELEMENT_TICKS_TOOLTIP"] = "Set the ticks for the X/Y axis.";
  Blockly.Msg["TSUMICKY_MPL_CHART_ELEMENT_TICK_LABELS"] = "for the graph at row %1 column %2, set the %3 %4 scale to %5 %6 and the label to %7 %8";
  Blockly.Msg["TSUMICKY_MPL_CHART_ELEMENT_TICK_LABELS_TOOLTIP"] = "Set the scale and labels for the X and Y axes.";
  Blockly.Msg["TSUMICKY_MPL_CHART_ELEMENT_TICK_LIST"] = "start %1 end %2 steps %3";
  Blockly.Msg["TSUMICKY_MPL_CHART_ELEMENT_TICK_LIST_TOOLTIP"] = "The axis tick marks are evenly spaced from the start value to the end value.";
  Blockly.Msg["TSUMICKY_MPL_CHART_ELEMENT_LIM"] = "for the chart at row %1 column %2 the range of %3 %4 is %5 to %6 %7";
  Blockly.Msg["TSUMICKY_MPL_CHART_ELEMENT_LIM_TOOLTIP"] = "Set the range of the X-axis and Y-axis scales.";
  Blockly.Msg["TSUMICKY_MPL_CHART_ELEMENT_GRID"] = "add grid to the chart at row %1 and column %2 %3 line width %4 line style %5 %6 line color %7 position %8 %9";
  Blockly.Msg["TSUMICKY_MPL_CHART_ELEMENT_GRID_TOOLTIP"] = "Draw grid on the chart.";
  Blockly.Msg["TSUMICKY_MPL_CHART_ELEMENT_GRID_BOTH"] = "both X/Y axes";
  Blockly.Msg["TSUMICKY_MPL_CHART_ELEMENT_GRID_X"] = "X axis only";
  Blockly.Msg["TSUMICKY_MPL_CHART_ELEMENT_GRID_Y"] = "Y axis only";
};