export function addMessages() {
  Blockly.Msg["TSUMICKY_CATEGORY_WBB_BROWSER"] = "Browser";
  Blockly.Msg["TSUMICKY_BROWSER_OPEN"] = "browser windows URL %1 width%2 height %3";
  Blockly.Msg["TSUMICKY_BROWSER_OPEN_TOOLTIP"] = "Get the result of opening browser window.";
  Blockly.Msg["TSUMICKY_BROWSER_CLOSE"] = "close window %1";
  Blockly.Msg["TSUMICKY_BROWSER_CLOSE_TOOLTIP"] = "Close browser window.";
  Blockly.Msg["TSUMICKY_BROWSER_NAVIGATE"] = "navigate to URL %2 in window %1";
  Blockly.Msg["TSUMICKY_BROWSER_NAVIGATE_TOOLTIP"] = "Navigate to the specified URL in a browser window.";
  Blockly.Msg["TSUMICKY_BROWSER_ALERT"] = "alert %2 in window %1";
  Blockly.Msg["TSUMICKY_BROWSER_ALERT_TOOLTIP"] = "Show the alert in a window.";
  Blockly.Msg["TSUMICKY_BROWSER_SELECT"] = "element with selector %2 in window %1";
  Blockly.Msg["TSUMICKY_BROWSER_SELECT_TOOLTIP"] = "Get the element specified by the selector in window.";
  Blockly.Msg["TSUMICKY_BROWSER_FIND"] = "elements inner %1 with selector %2";
  Blockly.Msg["TSUMICKY_BROWSER_FIND_TOOLTIP"] = "Get elements within an element that match a selector.";
  Blockly.Msg["TSUMICKY_BROWSER_CREATE_ELEMENT"] = "element created from HTML in %1";
  Blockly.Msg["TSUMICKY_BROWSER_CREATE_ELEMENT_TOOLTIP"] = "Get the created element from HTML.";
  Blockly.Msg["TSUMICKY_BROWSER_SET_INNER"] = "set inner %2 of %1 to %3";
  Blockly.Msg["TSUMICKY_BROWSER_SET_INNER_TOOLTIP"] = "Set the inner HTML or text of the element.";
  Blockly.Msg["TSUMICKY_BROWSER_GET_INNER"] = "get inner %2 of %1";
  Blockly.Msg["TSUMICKY_BROWSER_GET_INNER_TOOLTIP"] = "Get the inner HTML or text of the element.";
  Blockly.Msg["TSUMICKY_BROWSER_INNER_TEXT"] = "text";
  Blockly.Msg["TSUMICKY_BROWSER_SET_VALUE"] = "set %2 value to %1";
  Blockly.Msg["TSUMICKY_BROWSER_SET_VALUE_TOOLTIP"] = "Set the value of an input element.";
  Blockly.Msg["TSUMICKY_BROWSER_GET_VALUE"] = "get value of %1";
  Blockly.Msg["TSUMICKY_BROWSER_GET_VALUE_TOOLTIP"] = "Get the value of an input element.";
  Blockly.Msg["TSUMICKY_BROWSER_GET_SELECTED_TEXT"] = "The string of the item selected by select %1";
  Blockly.Msg["TSUMICKY_BROWSER_GET_SELECTED_TEXT_TOOLTIP"] = "Get the string of the selected item in a select element.";
  Blockly.Msg["TSUMICKY_BROWSER_GET_CHECKED_VALUE"] = "value of the checked item on radio button %1";
  Blockly.Msg["TSUMICKY_BROWSER_GET_CHECKED_VALUE_TOOLTIP"] = "Get the value of the selected radio button.";
  Blockly.Msg["TSUMICKY_BROWSER_SET_CHECKED"] = "Set the checked property of %1 to %2";
  Blockly.Msg["TSUMICKY_BROWSER_SET_CHECKED_TOOLTIP"] = "Set the checked property of a checkbox/radio.";
  Blockly.Msg["TSUMICKY_BROWSER_GET_CHECKED"] = "Get the checked property of %1";
  Blockly.Msg["TSUMICKY_BROWSER_GET_CHECKED_TOOLTIP"] = "Get the checked property of a checkbox/radio.";
  Blockly.Msg["TSUMICKY_BROWSER_ADD_ELEMENT"] = "add %3 %2 %1";
  Blockly.Msg["TSUMICKY_BROWSER_ADD_ELEMENT_TOOLTIP"] = "Add elements before, after, or inside another element.";
  Blockly.Msg["TSUMICKY_BROWSER_ADD_ELEMENT_AFTER"] = "after";
  Blockly.Msg["TSUMICKY_BROWSER_ADD_ELEMENT_BEFORE"] = "before";
  Blockly.Msg["TSUMICKY_BROWSER_ADD_ELEMENT_APPEND"] = "as the last child element of";
  Blockly.Msg["TSUMICKY_BROWSER_ADD_ELEMENT_PREPEND"] = "as the first child element of";
  Blockly.Msg["TSUMICKY_BROWSER_REMOVE_ELEMENT"] = "remove %1";
  Blockly.Msg["TSUMICKY_BROWSER_REMOVE_ELEMENT_TOOLTIP"] = "Remove an element.";
  Blockly.Msg["TSUMICKY_BROWSER_ADD_CLASS"] = "add class %2 to %1";
  Blockly.Msg["TSUMICKY_BROWSER_ADD_CLASS_TOOLTIP"] = "Add class to an element.";
  Blockly.Msg["TSUMICKY_BROWSER_REMOVE_CLASS"] = "remove class %2 from %1";
  Blockly.Msg["TSUMICKY_BROWSER_REMOVE_CLASS_TOOLTIP"] = "Remove class from an element.";
  Blockly.Msg["TSUMICKY_BROWSER_HAS_CLASS"] = "%1 has class %2";
  Blockly.Msg["TSUMICKY_BROWSER_HAS_CLASS_TOOLTIP"] = "Get whether an element has a specified class.";
  Blockly.Msg["TSUMICKY_BROWSER_SET_CSS"] = "set CSS %2 property of %1 to %3"
  Blockly.Msg["TSUMICKY_BROWSER_SET_CSS_TOOLTIP"] = "Set a CSS property for an element."
  Blockly.Msg["TSUMICKY_BROWSER_GET_CSS"] = "get CSS %2 property of %1"
  Blockly.Msg["TSUMICKY_BROWSER_GET_CSS_TOOLTIP"] = "Get the CSS property of an element."
  Blockly.Msg["TSUMICKY_BROWSER_SET_ATTR"] = "set %2 attribute of %1 to %3"
  Blockly.Msg["TSUMICKY_BROWSER_SET_ATTR_TOOLTIP"] = "Set the attribute of an element."
  Blockly.Msg["TSUMICKY_BROWSER_GET_ATTR"] = "get %2 attribute of %1"
  Blockly.Msg["TSUMICKY_BROWSER_GET_ATTR_TOOLTIP"] = "Get the attribute of an element."
  Blockly.Msg["TSUMICKY_BROWSER_REMOVE_ATTR"] = "remove %2 attribute from %1"
  Blockly.Msg["TSUMICKY_BROWSER_REMOVE_ATTR_TOOLTIP"] = "Remove the attribute from an element."
  Blockly.Msg["TSUMICKY_BROWSER_ON"] = "when %1 is %2 : parameter %3 %4 %5";
  Blockly.Msg["TSUMICKY_BROWSER_ON_TOOLTIP"] = "Set an event handler for an element.";
  Blockly.Msg["TSUMICKY_BROWSER_ON_CLICK"] = "clicked";
  Blockly.Msg["TSUMICKY_BROWSER_ON_MOUSEMOVE"] = "is the mousemove state";
  Blockly.Msg["TSUMICKY_BROWSER_ON_CHANGE"] = "changed";
  Blockly.Msg["TSUMICKY_BROWSER_ON_FOCUS"] = "focused";
  Blockly.Msg["TSUMICKY_BROWSER_ON_BLUR"] = "blured";
  Blockly.Msg["TSUMICKY_BROWSER_ON_KEYDOWN"] = "in the keydown state";
  Blockly.Msg["TSUMICKY_BROWSER_ON_KEYUP"] = "in the keyup state";
  Blockly.Msg["TSUMICKY_BROWSER_EVENT_PROPERTY"] = "%2 property of %1";
  Blockly.Msg["TSUMICKY_BROWSER_EVENT_PROPERTY_TOOLTIP"] = "Get the event property.";
};
