export function addMessages() {
  Blockly.Msg["TSUMICKY_CATEGORY_WBB_BROWSER"] = "ブラウザ";
  Blockly.Msg["TSUMICKY_BROWSER_OPEN"] = "ブラウザのウィンドウ URL %1 幅 %2 高さ %3";
  Blockly.Msg["TSUMICKY_BROWSER_OPEN_TOOLTIP"] = "ブラウザのウィンドウを開いた結果を得ます。";
  Blockly.Msg["TSUMICKY_BROWSER_CLOSE"] = "ウィンドウ %1 を閉じる";
  Blockly.Msg["TSUMICKY_BROWSER_CLOSE_TOOLTIP"] = "ウィンドウを閉じます。";
  Blockly.Msg["TSUMICKY_BROWSER_NAVIGATE"] = "ウィンドウ %1 で %2 のURLに移動";
  Blockly.Msg["TSUMICKY_BROWSER_NAVIGATE_TOOLTIP"] = "ウィンドウで、指定のURLのページに移動します。";
  Blockly.Msg["TSUMICKY_BROWSER_ALERT"] = "ウィンドウ %1 で %2 のアラートを表示";
  Blockly.Msg["TSUMICKY_BROWSER_ALERT_TOOLTIP"] = "ウィンドウ上でアラートを表示します。";
  Blockly.Msg["TSUMICKY_BROWSER_SELECT"] = "ウィンドウ %1 のセレクタが %2 の要素";
  Blockly.Msg["TSUMICKY_BROWSER_SELECT_TOOLTIP"] = "ウィンドウ内にあるセレクタで指定した要素を得ます。";
  Blockly.Msg["TSUMICKY_BROWSER_FIND"] = "%1 以下でセレクタが %2 の要素";
  Blockly.Msg["TSUMICKY_BROWSER_FIND_TOOLTIP"] = "ある要素の中で、セレクタに合致する要素を得ます。";
  Blockly.Msg["TSUMICKY_BROWSER_CREATE_ELEMENT"] = "%1 のHTMLから作成した要素";
  Blockly.Msg["TSUMICKY_BROWSER_CREATE_ELEMENT_TOOLTIP"] = "HTMLから作成した要素をを得ます。";
  Blockly.Msg["TSUMICKY_BROWSER_SET_INNER"] = "%1 の内部の %2 を %3 にする";
  Blockly.Msg["TSUMICKY_BROWSER_SET_INNER_TOOLTIP"] = "要素内のHTMLまたはテキストを設定します。";
  Blockly.Msg["TSUMICKY_BROWSER_GET_INNER"] = "%1 の内部の %2";
  Blockly.Msg["TSUMICKY_BROWSER_GET_INNER_TOOLTIP"] = "要素内のHTMLまたはテキストを得ます。";
  Blockly.Msg["TSUMICKY_BROWSER_INNER_TEXT"] = "テキスト";
  Blockly.Msg["TSUMICKY_BROWSER_SET_VALUE"] = "%1 の値を %2 にする";
  Blockly.Msg["TSUMICKY_BROWSER_SET_VALUE_TOOLTIP"] = "input系要素の値を設定します。";
  Blockly.Msg["TSUMICKY_BROWSER_GET_VALUE"] = "%1 の値";
  Blockly.Msg["TSUMICKY_BROWSER_GET_VALUE_TOOLTIP"] = "input系要素の値を得ます。";
  Blockly.Msg["TSUMICKY_BROWSER_GET_SELECTED_TEXT"] = "select %1 で選択された項目の文字列";
  Blockly.Msg["TSUMICKY_BROWSER_GET_SELECTED_TEXT_TOOLTIP"] = "select要素で選択された項目の文字列を得ます。";
  Blockly.Msg["TSUMICKY_BROWSER_GET_CHECKED_VALUE"] = "ラジオボタン %1 でチェックされた項目の値";
  Blockly.Msg["TSUMICKY_BROWSER_GET_CHECKED_VALUE_TOOLTIP"] = "ラジオボタンで選択された項目の値を得ます。";
  Blockly.Msg["TSUMICKY_BROWSER_SET_CHECKED"] = "%1 のチェック状態を %2 にする";
  Blockly.Msg["TSUMICKY_BROWSER_SET_CHECKED_TOOLTIP"] = "checkbox/radioのチェック状態を変更します。";
  Blockly.Msg["TSUMICKY_BROWSER_GET_CHECKED"] = "%1 のチェック状態";
  Blockly.Msg["TSUMICKY_BROWSER_GET_CHECKED_TOOLTIP"] = "checkbox/radioのチェック状態を取得します。";
  Blockly.Msg["TSUMICKY_BROWSER_ADD_ELEMENT"] = "%1 の %2 に %3 を追加";
  Blockly.Msg["TSUMICKY_BROWSER_ADD_ELEMENT_TOOLTIP"] = "要素の前後や内部に別の要素を追加します。";
  Blockly.Msg["TSUMICKY_BROWSER_ADD_ELEMENT_AFTER"] = "後";
  Blockly.Msg["TSUMICKY_BROWSER_ADD_ELEMENT_BEFORE"] = "前";
  Blockly.Msg["TSUMICKY_BROWSER_ADD_ELEMENT_APPEND"] = "子要素の最後";
  Blockly.Msg["TSUMICKY_BROWSER_ADD_ELEMENT_PREPEND"] = "子要素の最初";
  Blockly.Msg["TSUMICKY_BROWSER_REMOVE_ELEMENT"] = "%1 を削除";
  Blockly.Msg["TSUMICKY_BROWSER_REMOVE_ELEMENT_TOOLTIP"] = "要素を削除します。";
  Blockly.Msg["TSUMICKY_BROWSER_ADD_CLASS"] = "%1 にクラス %2 を追加"
  Blockly.Msg["TSUMICKY_BROWSER_ADD_CLASS_TOOLTIP"] = "要素にクラスを追加します。"
  Blockly.Msg["TSUMICKY_BROWSER_REMOVE_CLASS"] = "%1 からクラス %2 を削除"
  Blockly.Msg["TSUMICKY_BROWSER_REMOVE_CLASS_TOOLTIP"] = "要素からクラスを削除します。"
  Blockly.Msg["TSUMICKY_BROWSER_HAS_CLASS"] = "%1 にクラス %2 がついている"
  Blockly.Msg["TSUMICKY_BROWSER_HAS_CLASS_TOOLTIP"] = "要素に指定したクラスがついているどうかを得ます。"
  Blockly.Msg["TSUMICKY_BROWSER_SET_CSS"] = "%1 のCSSの %2 プロパティを %3 にする"
  Blockly.Msg["TSUMICKY_BROWSER_SET_CSS_TOOLTIP"] = "要素のCSSのプロパティを設定します。"
  Blockly.Msg["TSUMICKY_BROWSER_GET_CSS"] = "%1 のCSSの %2 プロパティの値"
  Blockly.Msg["TSUMICKY_BROWSER_GET_CSS_TOOLTIP"] = "要素のCSSのプロパティを得ます。"
  Blockly.Msg["TSUMICKY_BROWSER_SET_ATTR"] = "%1 の %2 属性を %3 にする"
  Blockly.Msg["TSUMICKY_BROWSER_SET_ATTR_TOOLTIP"] = "要素の属性を設定します。"
  Blockly.Msg["TSUMICKY_BROWSER_GET_ATTR"] = "%1 の %2 属性"
  Blockly.Msg["TSUMICKY_BROWSER_GET_ATTR_TOOLTIP"] = "要素の属性を得ます。"
  Blockly.Msg["TSUMICKY_BROWSER_REMOVE_ATTR"] = "%1 から %2 属性を削除"
  Blockly.Msg["TSUMICKY_BROWSER_REMOVE_ATTR_TOOLTIP"] = "要素から属性を削除します。"
  Blockly.Msg["TSUMICKY_BROWSER_ON"] = "%1 %2 とき：引数 %3 %4 %5"
  Blockly.Msg["TSUMICKY_BROWSER_ON_TOOLTIP"] = "要素のイベントハンドラを設定します。";
  Blockly.Msg["TSUMICKY_BROWSER_ON_CLICK"] = "がクリックされた";
  Blockly.Msg["TSUMICKY_BROWSER_ON_MOUSEMOVE"] = "の上でマウスポインタが動いた";
  Blockly.Msg["TSUMICKY_BROWSER_ON_CHANGE"] = "の値が変わった";
  Blockly.Msg["TSUMICKY_BROWSER_ON_FOCUS"] = "がフォーカスされた";
  Blockly.Msg["TSUMICKY_BROWSER_ON_BLUR"] = "のフォーカスが外れた";
  Blockly.Msg["TSUMICKY_BROWSER_ON_KEYDOWN"] = "でキーが押された";
  Blockly.Msg["TSUMICKY_BROWSER_ON_KEYUP"] = "でキーが離された";
  Blockly.Msg["TSUMICKY_BROWSER_EVENT_PROPERTY"] = "%1 の %2 プロパティ";
  Blockly.Msg["TSUMICKY_BROWSER_EVENT_PROPERTY_TOOLTIP"] = "イベントプロパティを得ます。";
};
