export function addMessages() {
  Blockly.Msg["TSUMICKY_CATEGORY_EXCEL_SHEET"] = "Excel sheet";
  Blockly.Msg["TSUMICKY_CATEGORY_EXCEL_SUB_SHEET"] = "Sheet";
  Blockly.Msg["TSUMICKY_EXCEL_ACTIVE_SHEET"] = "active sheet in %1";
  Blockly.Msg["TSUMICKY_EXCEL_ACTIVE_SHEET_TOOLTIP"] = "Get the active sheet of the specified workbook.";
  Blockly.Msg["TSUMICKY_EXCEL_SHEET_BY_INDEX"] = "sheet with index %2 in %1";
  Blockly.Msg["TSUMICKY_EXCEL_SHEET_BY_INDEX_TOOLTIP"] = "Get the sheet with the specified number in the workbook.";
  Blockly.Msg["TSUMICKY_EXCEL_SHEET_BY_NAME"] = "sheet with name %2 in %1";
  Blockly.Msg["TSUMICKY_EXCEL_SHEET_BY_NAME_TOOLTIP"] = "Get the sheet with the specified name in the workbook.";
  Blockly.Msg["TSUMICKY_EXCEL_SHEET_ADD"] = "add sheet to %1 and name it %2";
  Blockly.Msg["TSUMICKY_EXCEL_SHEET_ADD_TOOLTIP"] = "Add a sheet to the workbook and give it the specified name.";
  Blockly.Msg["TSUMICKY_EXCEL_SET_SHEET_DO"] = "process within the block using %1 as the target sheet %2 %3";
  Blockly.Msg["TSUMICKY_EXCEL_SET_SHEET_DO_TOOLTIP"] = "Process within the block, targeting the specified sheet. \nIn the block, you can specify a sheet in the 'target sheet' block.";
  Blockly.Msg["TSUMICKY_EXCEL_SET_SHEET_LOOP"] = "repeat the process in the block by sequentially selecting all sheets in %1 as target sheet %2 %3";
  Blockly.Msg["TSUMICKY_EXCEL_SET_SHEET_LOOP_TOOLTIP"] = "It sequentially retrieves all the sheets in the specified workbook, uses them as the target sheet, and repeats the process within the block. \nIn this block, you can specify the sheet by 'target sheet' block.";
  Blockly.Msg["TSUMICKY_EXCEL_CURRENT_SHEET"] = "target sheet";
  Blockly.Msg["TSUMICKY_EXCEL_CURRENT_SHEET_TOOLTIP"] = "Get the target sheet. \nIt can only be used within the 'process within the block using as the target sheet' and 'repeat the process in the block by sequentially selecting all sheets in as target sheet' blocks.";
  Blockly.Msg["TSUMICKY_EXCEL_SET_SHEET_NAME"] = "rename %1 to %2"
  Blockly.Msg["TSUMICKY_EXCEL_SET_SHEET_NAME_TOOLTIP"] = "Change the name of the target sheet."
  Blockly.Msg["TSUMICKY_EXCEL_SHEET_NAME"] = "name of %1";
  Blockly.Msg["TSUMICKY_EXCEL_SHEET_NAME_TOOLTIP"] = "Get the sheet name.";
  Blockly.Msg["TSUMICKY_EXCEL_SHEET_INDEX"] = "index of %1";
  Blockly.Msg["TSUMICKY_EXCEL_SHEET_INDEX_TOOLTIP"] = "Get the sheet index.";
  Blockly.Msg["TSUMICKY_EXCEL_SHEET_PARENT"] = "workbook to which %1 belongs";
  Blockly.Msg["TSUMICKY_EXCEL_SHEET_PARENT_TOOLTIP"] = "Get the workbook to which the sheet belongs.";
  Blockly.Msg["TSUMICKY_EXCEL_SHEETS"] = "list of sheets in %1";
  Blockly.Msg["TSUMICKY_EXCEL_SHEETS_TOOLTIP"] = "Get a list of sheets belonging to a workbook.";
  Blockly.Msg["TSUMICKY_EXCEL_SHEETS_COUNT"] = "number of sheets in %1";
  Blockly.Msg["TSUMICKY_EXCEL_SHEETS_COUNT_TOOLTIP"] = "Get the number of sheets belonging to a workbook.";
  Blockly.Msg["TSUMICKY_EXCEL_SET_SHEET_TAB_COLOR"] = "set tab color of %1 to %2";
  Blockly.Msg["TSUMICKY_EXCEL_SET_SHEET_TAB_COLOR_TOOLTIP"] = "Set the sheet tab color.";
  Blockly.Msg["TSUMICKY_EXCEL_RESET_SHEET_TAB_COLOR"] = "reset tab color of %1";
  Blockly.Msg["TSUMICKY_EXCEL_RESET_SHEET_TAB_COLOR_TOOLTIP"] = "Reset the sheet tab color.";
};
